### ISSUE TITLE
how generate the seqmap file ?

### ISSUE THREAD

**Issue by Tylerjoe** [VisualComputingInstitute/mots_tools#1]
If I want to test my own video, how should I generate the seqmap, because I know the meaning of the paramters in the seqmap file

**Comment by pvoigtlaender** [comment]
Hi,

the seqmap format comes from KITTI.
The format is very simple, for each line you have
<seq_id> empty <start_frame> <end_frame>
for example
0000 empty 000000 000153

**Comment by Tylerjoe** [comment]
@pvoigtlaender ok, Thank you very much
