### ISSUE TITLE
Use of annotation procedure MOTS for own dataset

### ISSUE THREAD

**Issue by jong372** [VisualComputingInstitute/mots_tools#10]
I want to apply the TrackR-CNN for **apple** detection and tracking. Hence, I need to build a dataset from scratch. For annotation you make use of .png and .txt files, but I'm not able to reproduce your annotation procedure (due to your automatic annotation). This leaves me with some questions;

- Can the .png mask be compared with other .png masks (like PASCAL VOC), or does your mask contain extra information?
- Do you use open source annotation tools for the final step of manual annotation (which e.g. exports your required .png format)?
- Are your masks transferable to other domains (e.g can it be converted to xml, json etc.)?

**Comment by ahnonay** [comment]
See https://github.com/VisualComputingInstitute/TrackR-CNN/issues/89
