### ISSUE TITLE
Sometimes it reports error "Something went wrong! FN is negative". Why does it happen?

### ISSUE THREAD

**Issue by zHaOshuAnGye** [VisualComputingInstitute/mots_tools#11]
Hello~Thanks for your code.It's very nice. When using it , I encountered the above problems.
I saw the source  code,“tmpfn += len(g) - num_associations”，this line，but I don't know why sometimes len(g) is less than num_associations. I want to ask that under what circumstances can it happen. It shouldn't have happened in theory.

**Comment by zHaOshuAnGye** [comment]
Maybe it is because gg may match more than one mask in tt? Can I add a "break" at end of this loop, which means gg only match the first mask meeting in tt.
![image](https://user-images.githubusercontent.com/38178828/95936494-48de7d80-0e08-11eb-89c5-1df81cc5d1ad.png)

**Comment by ahnonay** [comment]
There should be only one predicted mask having IoU above 0.5 with a ground truth mask if all predicted masks are non-overlapping. How are you calling compute_MOTS_metrics_per_sequence? Are you calling it via eval.py?

**Comment by ahnonay** [comment]
Closing this for now, please reopen if needed
