### ISSUE TITLE
Error when run the command 'python mots_eval/eval.py tracking_results gt_folder seqmap'

### ISSUE THREAD

**Issue by CommandoHuan** [VisualComputingInstitute/mots_tools#12]
When i ran the command 'python mots_eval/eval.py tracking_results gt_folder seqmap', it raise error:

Traceback (most recent call last):
  File "mots_eval/eval.py", line 3, in <module>
    from mots_common.io import load_seqmap, load_sequences
ModuleNotFoundError: No module named 'mots_common'

The module 'mots_common' cannot install whit pip.
How can i do now? pls help me

**Comment by CommandoHuan** [comment]
Another question: Can author show the tree list of project. I don't know how to organize the images and annotations. Thanks a lot.

**Comment by pvoigtlaender** [comment]
Please try to put the current directory into your pythonpath before you start the eval script:
`export PATH=${PATH}:${PWD}`

For the file tree:
```
KITTI_MOTS/train
  images/
     0000/
     0001/
    ....
  instances/
     0000/
     0001/
    ....
  instances_txt/
   0000.txt
   0001.txt
   ...
```

**Comment by CommandoHuan** [comment]
> export PATH=${PATH}:${PWD}

Thank you very much.

**Comment by CommandoHuan** [comment]
> Please try to put the current directory into your pythonpath before you start the eval script:
> `export PATH=${PATH}:${PWD}`
> 
> For the file tree:
> 
> ```
> KITTI_MOTS/train
>   images/
>      0000/
>      0001/
>     ....
>   instances/
>      0000/
>      0001/
>     ....
>   instances_txt/
>    0000.txt
>    0001.txt
>    ...
> ```

Can you show me the full tree list of project? I'm a newbie and don't know where to put KITTI_MOTS folder.

**Comment by pvoigtlaender** [comment]
The KITTI_MOTS folder doesn't have to be at a specific directory. When you run a script, you need to provide the path to the dataset as an argument.

**Comment by CommandoHuan** [comment]
> The KITTI_MOTS folder doesn't have to be at a specific directory. When you run a script, you need to provide the path to the dataset as an argument.

Thank you. But what is the parameter that fit with KITTI_MOTS in the command 'python mots_eval/eval.py tracking_results gt_folder seqmap'

**Comment by pvoigtlaender** [comment]
gt_folder here is KITTI_MOTS/instances_txt/

**Comment by ahnonay** [comment]
Closing this for now, please reopen if needed
