### ISSUE TITLE
about mots_eval/visualize_mots.py

### ISSUE THREAD

**Issue by 1wanttoknow** [VisualComputingInstitute/mots_tools#2]
There is no “visualize_mots.py” file in the code。How do I get it？Thank you！

**Comment by pvoigtlaender** [comment]
it's in the mots_vis subfolder:
https://github.com/VisualComputingInstitute/mots_tools/blob/master/mots_vis/visualize_mots.py

**Comment by 1wanttoknow** [comment]
thank you very much！
