### ISSUE TITLE
Evaluating a tracking result

### ISSUE THREAD

**Issue by SamihaSara** [VisualComputingInstitute/mots_tools#3]
I am trying to understand the evaluation codes. I have not run the track-RCNN yet.  I am facing the following error While trying to run. Please suggest me some solutions to this error. Can anyone please tell how to input seqmap ? I have not changed the seqmap files from mots_eval.

![Capture](https://user-images.githubusercontent.com/9627710/70981866-30b2aa80-20e0-11ea-9b83-ee56995201fb.PNG)

**Comment by pvoigtlaender** [comment]
Hi,

can you please show the call of the script including the passed command line arguments?

**Comment by SamihaSara** [comment]
Thanks for replying. I am in the **Evaluating a tracking result** section. Here is the command and then the error messages I am getting. 

![Capture](https://user-images.githubusercontent.com/9627710/71045228-6b5b2800-215e-11ea-9eea-06973e4dd0f8.PNG)

![Capture](https://user-images.githubusercontent.com/9627710/71045846-b5dda400-2160-11ea-9632-19742ef2dcaa.PNG)



Here seqmap file is exactly copied from fulltrain.seqmap , gt_folder has Annotations in txt format and tracking_results is copied from TrackR-CNN tracking result.  I have tried with Annotations in png format but getting the same error.  Please let me know what I am doing wrong

**Comment by SamihaSara** [comment]
After adding a breakpoint in **io.py** (from mots_common) here is the output after print()

![Capture](https://user-images.githubusercontent.com/9627710/71154483-c9befe00-2265-11ea-8d9b-4c5bc5294247.PNG)

**Comment by pvoigtlaender** [comment]
We resolved this issue via email.

**Comment by jsh-me** [comment]
Hello
I have the same problem. Can you tell me what you did to fix it?
I hope to solve this problem:( Thanks.

**Comment by pvoigtlaender** [comment]
Hi @jsh-me Are you trying to eval MOTSChallenge or KITTI MOTS?
