### ISSUE TITLE
How to visualize the tracking result on avi vedio file?

### ISSUE THREAD

**Issue by sisrfeng** [VisualComputingInstitute/mots_tools#4]
in the readme:
where "img_folder" is a folder containing the original KITTI tracking images
Do I need to transfer the avi vedio file (from CityFlow dataset)  to image?

**Comment by ahnonay** [comment]
Yes, our tool only supports visualizing on images, so you would need to extract the video frames first

**Comment by ahnonay** [comment]
Closing this for now, please reopen if needed
